// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	socketTraceMapEvents              = "events"
	socketTraceProgKprobeTcpV4Connect = "kprobe__tcp_v4_connect"
)

// loadSocketTrace returns the embedded CollectionSpec for socketTrace.
func loadSocketTrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SocketTraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load socketTrace: %w", err)
	}

	return spec, err
}

// loadSocketTraceObjects loads socketTrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*socketTraceObjects
//	*socketTracePrograms
//	*socketTraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSocketTraceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSocketTrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// socketTraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTraceSpecs struct {
	socketTraceProgramSpecs
	socketTraceMapSpecs
	socketTraceVariableSpecs
}

// socketTraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTraceProgramSpecs struct {
	KprobeTcpV4Connect *ebpf.ProgramSpec `ebpf:"kprobe__tcp_v4_connect"`
}

// socketTraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// socketTraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type socketTraceVariableSpecs struct {
}

// socketTraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSocketTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTraceObjects struct {
	socketTracePrograms
	socketTraceMaps
	socketTraceVariables
}

func (o *socketTraceObjects) Close() error {
	return _SocketTraceClose(
		&o.socketTracePrograms,
		&o.socketTraceMaps,
	)
}

// socketTraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSocketTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *socketTraceMaps) Close() error {
	return _SocketTraceClose(
		m.Events,
	)
}

// socketTraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSocketTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTraceVariables struct {
}

// socketTracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSocketTraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type socketTracePrograms struct {
	KprobeTcpV4Connect *ebpf.Program `ebpf:"kprobe__tcp_v4_connect"`
}

func (p *socketTracePrograms) Close() error {
	return _SocketTraceClose(
		p.KprobeTcpV4Connect,
	)
}

func _SocketTraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sockettrace_bpf.o
var _SocketTraceBytes []byte
