name: Gateway CI

on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]


jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencis
        run: |
          cd gateway-go
          go mod download

      - name: Run Linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
          working-directory: gateway-go

      - name: Run Unit Tests with Coverage
        run: |
          cd gateway-go
          go test -v -coverprofile=coverage.out ./...


